version: "3.8"
services:
  db:
    image: mongo
    container_name: "mongodb"
    env_file: .env
    environment: 
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
      - "./mongodb:/data/db"
