version: "3.8"
services:
  db:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=process.env.MONGO_DATABASE
      # - MONGO_INITDB_ROOT_USERNAME=process.env.MONGO_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD=process.env.MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      # - "./init:/docker-entrypoint-initdb.d"
      - "./nutriguide_mongodb:/data/db"
