version: "3.8"
services:
  db:
    image: mongo
    container_name: "mongodb"
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "./src/database/init:/docker-entrypoint-initdb.d"
      - "./mongodb:/data/db"
    networks:
      - nutriguide

  backend:
    image: "pruebita"
    build: .
    container_name: "nutriguide"
    depends_on:
      - db
    environment:
      MONGO_URL: db
    ports:
      - "8080:8080"
    networks:
      - nutriguide

networks:
  nutriguide:
    name: "nutriguide_network"
