version: "3.8"
services:
  db:
    image: mongo:4.4.6
    container_name: "mongodb"
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "./mongodb:/data/db"
      - "./data:/docker-entrypoint-initdb.d"
    networks:
      - nutriguide

  backend:
    image: nutriguide-backend
    container_name: "nutriguide"
    depends_on:
      - db
    environment:
      MONGO_URL: db
      ENV: local
    ports:
      - "5000:5000"
    networks:
      - nutriguide

networks:
  nutriguide:
    name: "nutriguide_network"
