version: "3.8"
services:
  db:
    image: mongo:4.4.6
    container_name: "mongodb"
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "./mongodb:/data/db"
      - "./init:/docker-entrypoint-initdb.d"
    networks:
      - nutriguide

  backend:
    image: registry.digitalocean.com/nutriguide/nutriguide-backend
    container_name: "nutriguide"
    depends_on:
      - db
    environment:
      ENV: prod
      MONGO_USERNAME: z02Fit0
      MONGO_PASSWORD: 4pSAD4DkyE7G
      MONGO_DATABASE: nutriguide
      MONGO_PORT: 27017
      MONGO_URL: localhost

    ports:
      - "8080:8080"
    networks:
      - nutriguide

networks:
  nutriguide:
    name: "nutriguide_network"
