name: Deployment

on:
  push:
    inputs:
      version:
        description: 'Image version'
        required: true
  # pull_request:
  #   branches:
  #     - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build . -t nutriguide-backend
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag nutriguide-backend registry.digitalocean.com/nutriguide/nutriguide-backend
          # docker tag registry.digitalocean.com/nutriguide/nutriguide-backend \
          # registry.digitalocean.com/nutriguide/nutriguide-backend:${{ github.event.inputs.version }}
      - name: Push image to DO Container Registry
        # run: docker push registry.digitalocean.com/nutriguide/nutriguide-backend:${{ github.event.inputs.version }}
        run: docker push ${{ secrets.DOCKER_IMAGE_REGISTRY }}

  run_new_app_containers:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_ElENA }}
        key: ${{ secrets.DROPLET_ELENA_KEY }}
        script: docker pull ${{ secrets.DOCKER_IMAGE_REGISTRY }}:latest
