name: Deployment

on: [push]
  # pull_request:
  #   branches:
  #     - main

jobs:

  digital_ocean_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
    - name: Try command
      run: doctl compute droplet get debian-nutriguide --output json
