name: Deployment

on: [push]
  # pull_request:
  #   branches:
  #     - main

jobs:

  digital_ocean_deployment:
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ DIGITALOCEAN_TOKEN }}
    - name: Try command
      run: doctl compute droplet get droplet_it --output json
